spring:
  application:
    name: nt-ms
---
server:
  port: 9002
  ssl:
    enabled: true
    client-auth: need
    key-store: classpath:nt-ms.jks
    key-store-password: nt-service
    key-alias: nt-ms
    key-store-type: JKS
    key-store-provider: SUN
    trust-store: classpath:nt-ms.jks
    trust-store-password: nt-service
    trust-store-type: JKS